### ISSUE TITLE
Unstick all WAS Seed Preassembly WFs

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/was_robot_suite#682] opened 2024-03-25 13:49 UTC
To allow changes to the accession WF, all existing WAS Seed Preassembly WFs must be completed or the workflows deleted.

See https://argo.stanford.edu/catalog?f%5Bwf_wps_ssim%5D%5B%5D=wasSeedPreassemblyWF%3Athumbnail-generator%3Aerror

**Comment by andrewjbtw** [comment] 2024-03-25 16:02
How do these items block changes to accessionWF?

**Comment by andrewjbtw** [comment] 2024-03-25 16:08
Oh, I think I get it, because this WF will send some XML files along, as it currently stands.

**Comment by justinlittman** [comment] 2024-03-25 16:09
Correct.

**Comment by lwrubel** [comment] 2024-03-25 21:10
@peterchanws is working with @andrewjbtw to purge those that are not in SWAP.

**Comment by andrewjbtw** [comment] 2024-03-25 22:07
I'm down to 5 problem druids. Four can't be purged because there's already an accessioned version, so I will decommission them. 

The fifth one is tricky because it's in SWAP but the thumbnail generation is timing out: https://argo.stanford.edu/view/druid:sk951fp2241

I think the problem is that the first capture doesn't render quickly (or possibly at all) and that's what thumbnail generation looks for. I'm able to load the second capture and we could create a manually-generated thumbnail if need be. That would mean accessioning the item through the Preassembly app while supplying a JP2 to go with it. It wouldn't use the WAS worklfow at all.

**Comment by lwrubel** [comment] 2024-03-26 16:00
I think you are right about there being a problem with replay of the first capture. I retried a couple of times, including after restarting Pywb to catch it while it had less crawler traffic, and that did not help.

**Comment by lwrubel** [comment] 2024-03-26 17:06
@justinlittman nothing remains stuck in an Error/Waiting state in the wasSeedPreassemblyWF thanks to @andrewjbtw and @peterchanws's work. Closing the ticket.

**Closed by lwrubel** 2024-03-26 17:06 UTC
