### ISSUE TITLE
cron job to clean out old files from cdx_backup directory

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/was_robot_suite#73] opened 2017-07-27 19:21 UTC
Currently, `cdx_backup_directory` has a ton of stuff in it in prod:

```
[was@was-robots1-prod cdx_backup]$ ll -lrt | head
total 94804
drwxr-xr-x 2 was was   4096 Sep 12  2014 druid:qf593jg6933
drwxr-xr-x 2 was was   4096 Oct 21  2014 druid:wx794kg1767
drwxr-xr-x 2 was was   4096 Nov 12  2014 druid:rj777jj4091
drwxr-xr-x 2 was was   4096 Nov 13  2014 druid:mr667xz6670
drwxr-xr-x 2 was was   4096 Dec  2  2014 druid:wx768dh2133
drwxr-xr-x 2 was was 143360 Dec 19  2014 druid:gw768qy7377
drwxr-xr-x 2 was was   4096 Jan  8  2015 nz972cq6239
drwxr-xr-x 2 was was   4096 Jan 14  2015 wz203wd3598
drwxr-xr-x 2 was was  32768 Jan 21  2015 druid:dd828qv5090
```
We should have a cron to remove old stuff.  @nullhandle:  "shouldn't be a problem to blow away the cdx files, though - we can always regenerate"  (as they are all generating from WARCs)

Can use whenever gem (see config/schedule.rb) to set up a cron job to call a rake task that we would write for this.

**Comment by jcoyne** [comment] 2020-06-03 04:54
The directory in question is `/web-archiving-stacks/data/indices/cdx_backup/`

**Comment by jcoyne** [comment] 2020-06-03 04:57
Before we proceed with this, can we ask why we are putting these files in this directory?

https://github.com/sul-dlss/was_robot_suite/blob/bbf4e678c1df5363508df7c47274011a7e3c488f/lib/was_crawl_dissemination/cdx_merge_sort_publish_service.rb#L30

Maybe we should blow the directory away and change the code not to stash a copy here?

**Comment by ndushay** [comment] 2020-06-03 20:45
because if we screw up it takes days to rebuild the entire index?

**Comment by jcoyne** [comment] 2020-06-04 04:56
@ndushay so, if we screw up, is there a way to restore from the backup?

**Comment by ndushay** [comment] 2020-06-04 20:12
@jcoyne I believe we would move the same files back to the source directory from which they came.  Voila!

**Comment by jcoyne** [comment] 2020-06-04 20:22
@ndushay is that something we do regularly?  How would we know in which situations it would be appropriate to do this?  Is there a point at which there would be no advantage to keeping that backup?

**Comment by justinlittman** [comment] 2020-06-04 20:24
I would be real reluctant to touch anything related to CDX indexing. If we make a mistake, it will be a huge pain to recover. And given that we don't really understand how SWAP is supposed to work, it will be really hard to tell if we got it right.

**Comment by aaron-collier** [comment] 2020-06-05 16:07
Following the discussion above, do we want to do this?

**Comment by ndushay** [comment] 2020-06-06 00:02
i would say we don't want to remove actual cdx index backup files, but other cruft in there, especially if it's old, can go.

**Comment by mjgiarlo** [comment] 2022-05-23 16:37
We recommend holding off on considering these until after we're successfully switched over to pywb.

**Comment by ndushay** [comment] 2022-06-04 01:58
is this a dup of #44?

**Comment by mjgiarlo** [comment] 2022-06-05 03:45
> is this a dup of #44?

You seemed to think so ~5 years ago, at least! https://github.com/sul-dlss/was_robot_suite/issues/44#issuecomment-320844881

**Comment by lwrubel** [comment] 2022-07-14 18:45
Closing as a duplicate of #44.

**Closed by lwrubel** 2022-07-14 18:45 UTC
Labels: web archiving
